"""Comprehensive analysis of potential bugs"""
print("="*80)
print("COMPREHENSIVE BUG ANALYSIS")
print("="*80)
print()

print("1. COMMISSION DEDUCTION LOGIC:")
print("   - Commission is subtracted from realized_pnl at line 1332")
print("   - BUT: Commission is subtracted AFTER trade_pnl_amount is calculated")
print("   - Trade logging uses trade_pnl_amount (gross) but commission is separate")
print("   - Check if net_pnl = pnl - commission is calculated correctly in journal")
print()

print("2. REALIZED PNL ACCUMULATION:")
print("   - Line 994: realized_pnl += trade_pnl_amount (stop loss)")
print("   - Line 1160: realized_pnl += trade_pnl_amount (position reversed)")
print("   - Line 1219: realized_pnl += trade_pnl_amount (position closed)")
print("   - Line 1332: realized_pnl -= commission_cost (commission deduction)")
print("   - POTENTIAL ISSUE: Commission is subtracted ONCE per trade, but")
print("     trade_pnl_amount is added MULTIPLE times for same trade?")
print()

print("3. ENTRY PRICE MANAGEMENT:")
print("   - Entry price is set when opening position")
print("   - Entry price is cleared when closing position")
print("   - BUT: Is it cleared in ALL cases (stop loss, reversal, close)?")
print("   - Check if entry_price persists incorrectly between trades")
print()

print("4. TOTAL PNL CALCULATION:")
print("   - Line 1360: total_pnl = realized_pnl + unrealized_pnl")
print("   - This is correct IF:")
print("     - realized_pnl includes all closed trades (minus commissions)")
print("     - unrealized_pnl is for current open position only")
print("   - POTENTIAL ISSUE: Is unrealized_pnl reset when position closes?")
print()

print("5. EQUITY CURVE vs TRADING JOURNAL:")
print("   - Equity curve: initial_capital + total_pnl (per-episode)")
print("   - Trading journal: SUM(net_pnl) from all trades (cumulative)")
print("   - KNOWN ISSUE: Equity curve resets each episode, journal is cumulative")
print("   - Need to verify if equity calculation should be cumulative")
print()

print("6. COMMISSION CALCULATION:")
print("   - Fixed: Now charges only on entry (not exit)")
print("   - BUT: Check if commission is calculated correctly for reversals")
print("   - Reversals: Close old position (no commission) + Open new (commission)")
print()

print("7. STOP LOSS TRIGGERING:")
print("   - Fixed: Now checks loss from entry price")
print("   - BUT: Is it checked EVERY step when position is open?")
print("   - Check if stop loss is only checked when position_change happens")
print()

print("8. STATE RESET:")
print("   - Check if all state variables reset properly in reset()")
print("   - Especially: realized_pnl, total_pnl, entry_price, etc.")
print("   - Verify no state leaks between episodes")
print()

print("9. DUPLICATE TRADE LOGGING:")
print("   - Database shows duplicate trades (same timestamp)")
print("   - Check if trade_callback is called multiple times for same trade")
print("   - Verify trade logging is idempotent")
print()

print("10. TOTAL_PNL vs NET_PNL:")
print("    - Environment uses 'total_pnl' (realized + unrealized)")
print("    - Journal uses 'net_pnl' (pnl - commission)")
print("    - Are these consistent?")
print("    - Check if total_pnl already includes commission deduction")
print()

