"""Document the fix needed for P&L discrepancy"""
print("="*80)
print("P&L DISCREPANCY FIX PLAN")
print("="*80)
print()
print("ROOT CAUSE:")
print("1. Equity curve uses PER-EPISODE PnL (resets each episode)")
print("2. Trading journal sums ALL trades (cumulative)")
print("3. These are different scopes, causing $1.32M discrepancy")
print()
print("SOLUTION:")
print("Performance Monitor should calculate equity from cumulative trades:")
print("  equity = initial_capital + SUM(net_pnl from ALL trades in database)")
print()
print("This ensures:")
print("- Equity curve matches trading journal")
print("- Performance Monitor shows accurate cumulative P&L")
print("- No more discrepancies between dashboards")

